name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: make build

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          # modulesのキャッシュ
          ~/go/pkg/mod
          # ビルドキャッシュ（Linux）
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: test
      run: make test